// Documentação microscópica — Módulo ADMIN INTERNO (PagSmile back-office)
// Painel interno usado pela equipe da PagSmile para gerir merchants, compliance,
// risco, financeiro, comunicação e configurações globais.

import { AdminIntDashboardDoc } from './docs/adminInterno/AdminIntDashboard';

export const adminInternoModule = {
  id: 'admin-interno',
  label: 'Admin Interno',
  shortLabel: 'Back-office PagSmile',
  description: 'Painel utilizado pela equipe interna da PagSmile para gestão completa da operação: merchants, compliance, transações, financeiro, risco, relatórios, comunicação e administração da plataforma.',
  color: '#8b5cf6',
  iconName: 'ShieldCheck',
  sections: [
    {
      id: 'dashboard',
      label: 'Dashboard',
      pages: [
        { id: 'AdminIntDashboard', label: 'Dashboard Interno (10 views)', route: '/AdminIntDashboard', content: AdminIntDashboardDoc },
      ],
    },
    {
      id: 'compliance',
      label: 'Compliance',
      pages: [
        { id: 'AdminIntCompliance', label: 'Dashboard de Compliance', route: '/AdminIntCompliance', content: null },
        { id: 'AdminIntComplianceQueue', label: 'Fila de Compliance', route: '/AdminIntComplianceQueue', content: null },
        { id: 'AdminIntComplianceReview', label: 'Análise Manual', route: '/AdminIntComplianceReview', content: null },
        { id: 'AdminIntComplianceSubmissions', label: 'Submissões', route: '/AdminIntComplianceSubmissions', content: null },
        { id: 'AdminIntComplianceForms', label: 'Gestão de Formulários', route: '/AdminIntComplianceForms', content: null },
        { id: 'AdminIntComplianceDocs', label: 'Repositório de Documentos', route: '/AdminIntComplianceDocs', content: null },
        { id: 'AdminIntComplianceRules', label: 'Regras e Workflows', route: '/AdminIntComplianceRules', content: null },
        { id: 'AdminIntComplianceAudit', label: 'Auditoria de Compliance', route: '/AdminIntComplianceAudit', content: null },
        { id: 'AdminIntComplianceHelena', label: 'Helena IA (Treinamento)', route: '/AdminIntComplianceHelena', content: null },
        { id: 'AdminIntComplianceFormLink', label: 'Gerador de Link de Formulário', route: '/AdminIntComplianceFormLink', content: null },
      ],
    },
    {
      id: 'merchants',
      label: 'Merchants',
      pages: [
        { id: 'AdminIntMerchantsOverview', label: 'Gestão Comerciantes & Subcontas', route: '/AdminIntMerchantsOverview', content: null },
        { id: 'AdminIntMerchants', label: 'Dashboard de Merchants', route: '/AdminIntMerchants', content: null },
        { id: 'AdminIntMerchantsList', label: 'Lista de Merchants', route: '/AdminIntMerchantsList', content: null },
        { id: 'AdminIntMerchantProfile', label: 'Perfil 360° (25 abas)', route: '/AdminIntMerchantProfile', content: null },
        { id: 'AdminIntSubaccounts', label: 'Subcontas', route: '/AdminIntSubaccounts', content: null },
        { id: 'AdminIntLimitRequests', label: 'Solicitações de Limite', route: '/AdminIntLimitRequests', content: null },
        { id: 'AdminIntMerchantGroups', label: 'Grupos', route: '/AdminIntMerchantGroups', content: null },
        { id: 'AdminIntMerchantTags', label: 'Tags', route: '/AdminIntMerchantTags', content: null },
        { id: 'AdminIntMerchantReports', label: 'Relatórios de Merchants', route: '/AdminIntMerchantReports', content: null },
        { id: 'AdminIntNewMerchant', label: 'Novo Merchant', route: '/AdminIntNewMerchant', content: null },
      ],
    },
    {
      id: 'merchant-profile-tabs',
      label: 'Perfil 360° — 25 Abas',
      pages: [
        { id: 'TabResumo', label: 'Aba: Resumo', route: '/AdminIntMerchantProfile?tab=resumo', content: null },
        { id: 'TabDadosCadastrais', label: 'Aba: Dados Cadastrais', route: '/AdminIntMerchantProfile?tab=cadastrais', content: null },
        { id: 'TabKYC', label: 'Aba: KYC/KYB', route: '/AdminIntMerchantProfile?tab=kyc', content: null },
        { id: 'TabDocumentos', label: 'Aba: Documentos', route: '/AdminIntMerchantProfile?tab=documentos', content: null },
        { id: 'TabTaxas', label: 'Aba: Taxas', route: '/AdminIntMerchantProfile?tab=taxas', content: null },
        { id: 'TabLimites', label: 'Aba: Limites', route: '/AdminIntMerchantProfile?tab=limites', content: null },
        { id: 'TabConfiguracoes', label: 'Aba: Configurações', route: '/AdminIntMerchantProfile?tab=config', content: null },
        { id: 'TabFinanceiro', label: 'Aba: Financeiro', route: '/AdminIntMerchantProfile?tab=financeiro', content: null },
        { id: 'TabTransacoes', label: 'Aba: Transações', route: '/AdminIntMerchantProfile?tab=transacoes', content: null },
        { id: 'TabChargebacks', label: 'Aba: Chargebacks', route: '/AdminIntMerchantProfile?tab=chargebacks', content: null },
        { id: 'TabSaques', label: 'Aba: Saques', route: '/AdminIntMerchantProfile?tab=saques', content: null },
        { id: 'TabSplit', label: 'Aba: Split', route: '/AdminIntMerchantProfile?tab=split', content: null },
        { id: 'TabSubSellers', label: 'Aba: SubSellers', route: '/AdminIntMerchantProfile?tab=subsellers', content: null },
        { id: 'TabRecorrencia', label: 'Aba: Recorrência', route: '/AdminIntMerchantProfile?tab=recorrencia', content: null },
        { id: 'TabAntecipacao', label: 'Aba: Antecipação', route: '/AdminIntMerchantProfile?tab=antecipacao', content: null },
        { id: 'TabNotas', label: 'Aba: Notas Internas', route: '/AdminIntMerchantProfile?tab=notas', content: null },
        { id: 'TabComunicacoes', label: 'Aba: Comunicações', route: '/AdminIntMerchantProfile?tab=comunicacoes', content: null },
        { id: 'TabUsuarios', label: 'Aba: Usuários', route: '/AdminIntMerchantProfile?tab=usuarios', content: null },
        { id: 'TabClientUsers', label: 'Aba: Client Users', route: '/AdminIntMerchantProfile?tab=clientusers', content: null },
        { id: 'TabCredenciaisAPI', label: 'Aba: Credenciais API', route: '/AdminIntMerchantProfile?tab=api', content: null },
        { id: 'TabWebhooks', label: 'Aba: Webhooks', route: '/AdminIntMerchantProfile?tab=webhooks', content: null },
        { id: 'TabMEDs', label: 'Aba: MEDs', route: '/AdminIntMerchantProfile?tab=meds', content: null },
        { id: 'TabPerformance', label: 'Aba: Desempenho', route: '/AdminIntMerchantProfile?tab=performance', content: null },
        { id: 'TabRisco', label: 'Aba: Risco', route: '/AdminIntMerchantProfile?tab=risco', content: null },
        { id: 'TabAuditoria', label: 'Aba: Auditoria', route: '/AdminIntMerchantProfile?tab=auditoria', content: null },
        { id: 'TabMetodosPagamento', label: 'Aba: Métodos de Pagamento', route: '/AdminIntMerchantProfile?tab=metodos', content: null },
      ],
    },
    {
      id: 'transactions',
      label: 'Transações',
      pages: [
        { id: 'AdminIntTransactionsDashboard', label: 'Dashboard de Transações', route: '/AdminIntTransactionsDashboard', content: null },
        { id: 'AdminIntTransactionsList', label: 'Lista de Transações', route: '/AdminIntTransactionsList', content: null },
        { id: 'AdminIntTransactionDetail', label: 'Detalhe da Transação', route: '/AdminIntTransactionDetail', content: null },
        { id: 'AdminIntOrchestration', label: 'Orquestração', route: '/AdminIntOrchestration', content: null },
        { id: 'AdminIntBINAnalysis', label: 'Análise de BIN', route: '/AdminIntBINAnalysis', content: null },
        { id: 'AdminIntRetryIntelligence', label: 'Retry Intelligence', route: '/AdminIntRetryIntelligence', content: null },
        { id: 'AdminIntBatchProcessing', label: 'Processamento em Lote', route: '/AdminIntBatchProcessing', content: null },
        { id: 'AdminIntReconciliation', label: 'Reconciliação', route: '/AdminIntReconciliation', content: null },
        { id: 'AdminIntTransactionReports', label: 'Relatórios de Transações', route: '/AdminIntTransactionReports', content: null },
      ],
    },
    {
      id: 'financial',
      label: 'Financeiro',
      pages: [
        { id: 'AdminIntFinancialDashboard', label: 'Dashboard Financeiro', route: '/AdminIntFinancialDashboard', content: null },
        { id: 'AdminIntFinancialResults', label: 'Resultados Financeiros', route: '/AdminIntFinancialResults', content: null },
        { id: 'AdminIntClientProfitability', label: 'Rentabilidade por Cliente', route: '/AdminIntClientProfitability', content: null },
        { id: 'AdminIntConciliation', label: 'Conciliação', route: '/AdminIntConciliation', content: null },
        { id: 'AdminIntPaymentAgenda', label: 'Agenda de Pagamentos', route: '/AdminIntPaymentAgenda', content: null },
        { id: 'AdminIntSettlements', label: 'Settlements', route: '/AdminIntSettlements', content: null },
        { id: 'AdminIntWithdrawals', label: 'Saques', route: '/AdminIntWithdrawals', content: null },
        { id: 'AdminIntWithdrawalApprovals', label: 'Aprovações de Saque', route: '/AdminIntWithdrawalApprovals', content: null },
        { id: 'AdminIntAnticipations', label: 'Antecipações', route: '/AdminIntAnticipations', content: null },
        { id: 'AdminIntStatements', label: 'Extratos', route: '/AdminIntStatements', content: null },
        { id: 'AdminIntBalanceManagement', label: 'Gestão de Saldos', route: '/AdminIntBalanceManagement', content: null },
      ],
    },
    {
      id: 'risk',
      label: 'Risco',
      pages: [
        { id: 'AdminIntRiskDashboard', label: 'Dashboard de Risco', route: '/AdminIntRiskDashboard', content: null },
        { id: 'AdminIntFraudMonitoring', label: 'Monitoramento de Fraude', route: '/AdminIntFraudMonitoring', content: null },
        { id: 'AdminIntChargebacksList', label: 'Chargebacks', route: '/AdminIntChargebacksList', content: null },
        { id: 'AdminIntPreChargebacks', label: 'Pré-Chargebacks', route: '/AdminIntPreChargebacks', content: null },
        { id: 'AdminIntMEDsList', label: 'MEDs', route: '/AdminIntMEDsList', content: null },
        { id: 'AdminIntRiskRules', label: 'Regras de Risco', route: '/AdminIntRiskRules', content: null },
        { id: 'AdminIntControlLists', label: 'Listas de Controle', route: '/AdminIntControlLists', content: null },
        { id: 'AdminIntRiskAlerts', label: 'Alertas de Risco', route: '/AdminIntRiskAlerts', content: null },
        { id: 'AdminIntBlockages', label: 'Bloqueios', route: '/AdminIntBlockages', content: null },
        { id: 'AdminIntAntifraud', label: 'Antifraude', route: '/AdminIntAntifraud', content: null },
      ],
    },
    {
      id: 'reports',
      label: 'Relatórios',
      pages: [
        { id: 'AdminIntReportsHub', label: 'Hub de Relatórios', route: '/AdminIntReportsHub', content: null },
        { id: 'AdminIntReportsOperational', label: 'Operacionais', route: '/AdminIntReportsOperational', content: null },
        { id: 'AdminIntReportsFinancial', label: 'Financeiros', route: '/AdminIntReportsFinancial', content: null },
        { id: 'AdminIntReportsRisk', label: 'Risco', route: '/AdminIntReportsRisk', content: null },
        { id: 'AdminIntReportsCustom', label: 'Customizados', route: '/AdminIntReportsCustom', content: null },
        { id: 'AdminIntAnalytics', label: 'Analytics & BI', route: '/AdminIntAnalytics', content: null },
      ],
    },
    {
      id: 'communication',
      label: 'Comunicação',
      pages: [
        { id: 'AdminIntCommDashboard', label: 'Dashboard de Comunicação', route: '/AdminIntCommDashboard', content: null },
        { id: 'AdminIntCommAutomations', label: 'Automações de E-mail', route: '/AdminIntCommAutomations', content: null },
        { id: 'AdminIntCommTemplates', label: 'Templates', route: '/AdminIntCommTemplates', content: null },
        { id: 'AdminIntCommSMTP', label: 'Configuração SMTP', route: '/AdminIntCommSMTP', content: null },
        { id: 'AdminIntCommSenders', label: 'Remetentes', route: '/AdminIntCommSenders', content: null },
        { id: 'AdminIntCommLogs', label: 'Logs', route: '/AdminIntCommLogs', content: null },
      ],
    },
    {
      id: 'administration',
      label: 'Administração',
      pages: [
        { id: 'AdminIntSettings', label: 'Configurações Gerais', route: '/AdminIntSettings', content: null },
        { id: 'AdminIntUsers', label: 'Usuários', route: '/AdminIntUsers', content: null },
        { id: 'AdminIntProfiles', label: 'Perfis & Permissões', route: '/AdminIntProfiles', content: null },
        { id: 'AdminIntGlobalRates', label: 'Taxas Globais', route: '/AdminIntGlobalRates', content: null },
        { id: 'AdminIntRiskParams', label: 'Parâmetros de Risco', route: '/AdminIntRiskParams', content: null },
        { id: 'AdminIntIntegrations', label: 'Integrações', route: '/AdminIntIntegrations', content: null },
        { id: 'AdminIntTemplates', label: 'Templates', route: '/AdminIntTemplates', content: null },
        { id: 'AdminIntSystemLogs', label: 'Logs do Sistema', route: '/AdminIntSystemLogs', content: null },
        { id: 'AdminIntMCCs', label: 'MCCs', route: '/AdminIntMCCs', content: null },
        { id: 'AdminIntMCCsAnalysis', label: 'Análise de MCCs', route: '/AdminIntMCCsAnalysis', content: null },
        { id: 'AdminIntPartners', label: 'Parceiros & Custos', route: '/AdminIntPartners', content: null },
        { id: 'AdminIntFeePlans', label: 'Planos de Taxa', route: '/AdminIntFeePlans', content: null },
        { id: 'AdminIntAiAgents', label: 'Configuração de Agentes IA', route: '/AdminIntAiAgents', content: null },
      ],
    },
    {
      id: 'ai-agents',
      label: 'Agentes IA Internos',
      pages: [
        { id: 'AdminIntPagSmileCopilot', label: 'PagSmile Copilot', route: '/AdminIntPagSmileCopilot', content: null },
        { id: 'AdminIntPagSmileCopilotSettings', label: 'PagSmile Copilot — Settings', route: '/AdminIntPagSmileCopilotSettings', content: null },
        { id: 'AdminIntRecoveryAgent', label: 'Recovery Agent (Interno)', route: '/AdminIntRecoveryAgent', content: null },
        { id: 'AdminIntRecoveryAgentSettings', label: 'Recovery Agent — Settings', route: '/AdminIntRecoveryAgentSettings', content: null },
        { id: 'AdminIntConverterAgent', label: 'Converter Agent (Interno)', route: '/AdminIntConverterAgent', content: null },
        { id: 'AdminIntConverterAgentSettings', label: 'Converter Agent — Settings', route: '/AdminIntConverterAgentSettings', content: null },
        { id: 'AdminIntDisputeManager', label: 'Dispute Manager (Interno)', route: '/AdminIntDisputeManager', content: null },
        { id: 'AdminIntDisputeManagerSettings', label: 'Dispute Manager — Settings', route: '/AdminIntDisputeManagerSettings', content: null },
        { id: 'AdminIntIdentityOnboarder', label: 'Identity Onboarder', route: '/AdminIntIdentityOnboarder', content: null },
        { id: 'AdminIntIdentityOnboarderSettings', label: 'Identity Onboarder — Settings', route: '/AdminIntIdentityOnboarderSettings', content: null },
      ],
    },
  ],
};