// Mocks centralizados para Catálogos Mestres (Adquirentes / Bandeiras / Canais / Bancos / etc.)

// ================== ADQUIRENTES ==================
export const ACQUIRERS = [
  {
    id: 'acq_cielo',
    name: 'Cielo',
    logo: 'https://logodownload.org/wp-content/uploads/2014/05/cielo-logo-0.png',
    type: 'full_acquirer',
    country: 'Brasil',
    status: 'active',
    description: 'Adquirente full líder no varejo brasileiro, parceiro estratégico desde 2018. Forte cobertura em POS físico e e-commerce.',
    brands: ['visa', 'mastercard', 'elo', 'hipercard', 'amex'],
    channels: ['pos', 'ec', 'online', 'pix'],
    modalities: ['debit', 'credit', 'installments_merchant', 'installments_issuer'],
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_anticipation: true,
    supports_webhook: true,
    sla_credentialing_days: 2.5,
    approval_rate: 96.4,
    chargeback_rate: 0.18,
    tpv_monthly: 12_400_000_000,
    revenue_monthly: 9_800_000,
    merchants_linked: 4380,
    contract: { start: '2018-03-01', end: '2027-03-01', alert: false },
    commercial_manager: { name: 'Marcelo Andrade', email: 'marcelo@pagsmile.com' },
    spread_avg: 0.42,
  },
  {
    id: 'acq_rede',
    name: 'Rede (Itaú)',
    logo: 'https://logodownload.org/wp-content/uploads/2017/04/rede-logo.png',
    type: 'full_acquirer',
    country: 'Brasil',
    status: 'active',
    description: 'Adquirente full do Itaú, segundo maior em market share. Forte em POS varejo e segmentos premium.',
    brands: ['visa', 'mastercard', 'elo', 'hipercard', 'amex', 'diners'],
    channels: ['pos', 'ec', 'online'],
    modalities: ['debit', 'credit', 'installments_merchant', 'installments_issuer'],
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_anticipation: true,
    supports_webhook: true,
    sla_credentialing_days: 3.1,
    approval_rate: 95.8,
    chargeback_rate: 0.21,
    tpv_monthly: 9_800_000_000,
    revenue_monthly: 7_500_000,
    merchants_linked: 3120,
    contract: { start: '2019-06-01', end: '2026-06-01', alert: true },
    commercial_manager: { name: 'Patrícia Souza', email: 'patricia@pagsmile.com' },
    spread_avg: 0.38,
  },
  {
    id: 'acq_stone',
    name: 'Stone',
    logo: 'https://logodownload.org/wp-content/uploads/2019/06/stone-logo-0.png',
    type: 'full_acquirer',
    country: 'Brasil',
    status: 'active',
    description: 'Adquirente full focado em PME, forte em foodservice e varejo de pequeno porte. Excelente UX em POS smart.',
    brands: ['visa', 'mastercard', 'elo', 'hipercard'],
    channels: ['pos', 'ec', 'online', 'pix'],
    modalities: ['debit', 'credit', 'installments_merchant'],
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_anticipation: true,
    supports_webhook: true,
    sla_credentialing_days: 1.8,
    approval_rate: 97.1,
    chargeback_rate: 0.15,
    tpv_monthly: 7_200_000_000,
    revenue_monthly: 6_100_000,
    merchants_linked: 2840,
    contract: { start: '2020-01-15', end: '2027-01-15', alert: false },
    commercial_manager: { name: 'Rafael Lima', email: 'rafael@pagsmile.com' },
    spread_avg: 0.45,
  },
  {
    id: 'acq_getnet',
    name: 'Getnet',
    logo: 'https://logodownload.org/wp-content/uploads/2017/06/getnet-logo-0.png',
    type: 'full_acquirer',
    country: 'Brasil',
    status: 'active',
    description: 'Adquirente do Santander, equilibrada em POS e EC. Bom suporte a cross-border.',
    brands: ['visa', 'mastercard', 'elo', 'amex'],
    channels: ['pos', 'ec', 'online'],
    modalities: ['debit', 'credit', 'installments_merchant', 'installments_issuer'],
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_anticipation: false,
    supports_webhook: true,
    sla_credentialing_days: 4.2,
    approval_rate: 94.2,
    chargeback_rate: 0.24,
    tpv_monthly: 4_100_000_000,
    revenue_monthly: 3_200_000,
    merchants_linked: 1620,
    contract: { start: '2021-03-01', end: '2026-03-01', alert: true },
    commercial_manager: { name: 'Júlia Reis', email: 'julia@pagsmile.com' },
    spread_avg: 0.36,
  },
  {
    id: 'acq_sicredi',
    name: 'Sicredi (Sub-acquirer)',
    logo: 'https://logodownload.org/wp-content/uploads/2019/06/sicredi-logo.png',
    type: 'sub_acquirer',
    country: 'Brasil',
    status: 'active',
    description: 'Sub-acquirer com forte penetração em cooperativas no Sul. Volume menor mas estratégico em vertical agro.',
    brands: ['visa', 'mastercard', 'elo'],
    channels: ['pos', 'ec'],
    modalities: ['debit', 'credit', 'installments_merchant'],
    supports_3ds: true, ds_version: '1.0',
    supports_tokenization: false,
    supports_anticipation: false,
    supports_webhook: false,
    sla_credentialing_days: 6.5,
    approval_rate: 92.8,
    chargeback_rate: 0.32,
    tpv_monthly: 480_000_000,
    revenue_monthly: 420_000,
    merchants_linked: 280,
    contract: { start: '2022-08-01', end: '2025-08-01', alert: true },
    commercial_manager: { name: 'Eduardo Pires', email: 'eduardo@pagsmile.com' },
    spread_avg: 0.55,
  },
  {
    id: 'acq_safrapay',
    name: 'SafraPay',
    logo: 'https://logodownload.org/wp-content/uploads/2017/04/safra-pay-logo.png',
    type: 'full_acquirer',
    country: 'Brasil',
    status: 'homologation',
    description: 'Em fase de homologação técnica, expectativa de produção em Q3/2026.',
    brands: ['visa', 'mastercard', 'elo'],
    channels: ['pos'],
    modalities: ['debit', 'credit'],
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_anticipation: false,
    supports_webhook: true,
    sla_credentialing_days: null,
    approval_rate: null,
    chargeback_rate: null,
    tpv_monthly: 0,
    revenue_monthly: 0,
    merchants_linked: 0,
    contract: { start: '2026-01-01', end: null, alert: false },
    commercial_manager: { name: 'Ana Beatriz', email: 'ana@pagsmile.com' },
    spread_avg: null,
  },
];

// MDR mínimo (matriz bandeira × modalidade × parcelas) para um adquirente
export const ACQUIRER_MDR_MATRIX = {
  acq_cielo: [
    { brand: 'Visa', modality: 'Débito', installments: '1x', acquirer_cost: 0.95, our_min: 1.20, market_avg: 1.18, plans_at_min: 0 },
    { brand: 'Visa', modality: 'Crédito', installments: '1x', acquirer_cost: 1.85, our_min: 2.20, market_avg: 2.30, plans_at_min: 2 },
    { brand: 'Visa', modality: 'Crédito', installments: '2-6x', acquirer_cost: 2.45, our_min: 2.80, market_avg: 2.85, plans_at_min: 4 },
    { brand: 'Visa', modality: 'Crédito', installments: '7-12x', acquirer_cost: 2.95, our_min: 3.30, market_avg: 3.40, plans_at_min: 6 },
    { brand: 'Mastercard', modality: 'Débito', installments: '1x', acquirer_cost: 0.92, our_min: 1.15, market_avg: 1.18, plans_at_min: 1 },
    { brand: 'Mastercard', modality: 'Crédito', installments: '1x', acquirer_cost: 1.80, our_min: 2.15, market_avg: 2.25, plans_at_min: 3 },
    { brand: 'Mastercard', modality: 'Crédito', installments: '2-6x', acquirer_cost: 2.40, our_min: 2.75, market_avg: 2.80, plans_at_min: 5 },
    { brand: 'Mastercard', modality: 'Crédito', installments: '7-12x', acquirer_cost: 2.90, our_min: 3.25, market_avg: 3.35, plans_at_min: 7 },
    { brand: 'Elo', modality: 'Crédito', installments: '1x', acquirer_cost: 2.10, our_min: 2.45, market_avg: 2.50, plans_at_min: 1 },
    { brand: 'Elo', modality: 'Crédito', installments: '2-6x', acquirer_cost: 2.70, our_min: 3.10, market_avg: 3.15, plans_at_min: 2 },
    { brand: 'Hipercard', modality: 'Crédito', installments: '1x', acquirer_cost: 2.30, our_min: 2.65, market_avg: 2.70, plans_at_min: 0 },
    { brand: 'Amex', modality: 'Crédito', installments: '1x', acquirer_cost: 2.85, our_min: 3.30, market_avg: 3.40, plans_at_min: 0 },
  ],
};

// ================== BANDEIRAS DE CARTÃO ==================
export const CARD_BRANDS = [
  {
    id: 'brand_visa',
    name: 'Visa',
    logo: 'https://logodownload.org/wp-content/uploads/2017/05/visa-logo-0.png',
    type: 'credit',
    country_origin: 'EUA',
    coverage: 'Global',
    status: 'active',
    description: 'Bandeira global líder em volume processado. Suporta crédito, débito e modalidades premium.',
    supports_nfc: true, nfc_version: 'payWave 2.0',
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_installments: true,
    max_installments: 24,
    monitoring_programs: ['VAMP', 'VFMP'],
    chargeback_threshold_pct: 0.9,
    chargeback_threshold_high_pct: 1.8,
    current_chargeback_pct: 0.42,
    vetoed_mccs: ['7995', '5967'],
    tpv_monthly: 14_500_000_000,
    transactions_monthly: 18_400_000,
    approval_rate: 96.1,
    cancellation_rate: 0.31,
    interchange_avg: 1.85,
    scheme_fee_avg: 0.18,
    acquirer_fee_avg: 0.45,
    channel_distribution: { pos: 38, ec: 42, online: 14, pix: 6 },
    modality_distribution: { vista: 58, parc_lojista: 28, parc_emissor: 14 },
    health_score: 92,
  },
  {
    id: 'brand_mastercard',
    name: 'Mastercard',
    logo: 'https://logodownload.org/wp-content/uploads/2014/02/mastercard-logo-0.png',
    type: 'credit',
    country_origin: 'EUA',
    coverage: 'Global',
    status: 'active',
    description: 'Bandeira global, segunda em volume. Forte em e-commerce e mobile wallets.',
    supports_nfc: true, nfc_version: 'PayPass 2.0',
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_installments: true,
    max_installments: 24,
    monitoring_programs: ['BRAM', 'MEAP'],
    chargeback_threshold_pct: 1.0,
    chargeback_threshold_high_pct: 1.5,
    current_chargeback_pct: 0.51,
    vetoed_mccs: ['7995', '5967', '4900'],
    tpv_monthly: 11_200_000_000,
    transactions_monthly: 14_800_000,
    approval_rate: 95.7,
    cancellation_rate: 0.34,
    interchange_avg: 1.82,
    scheme_fee_avg: 0.17,
    acquirer_fee_avg: 0.43,
    channel_distribution: { pos: 35, ec: 45, online: 14, pix: 6 },
    modality_distribution: { vista: 55, parc_lojista: 30, parc_emissor: 15 },
    health_score: 88,
  },
  {
    id: 'brand_elo',
    name: 'Elo',
    logo: 'https://logodownload.org/wp-content/uploads/2014/06/elo-logo-cartao.png',
    type: 'credit',
    country_origin: 'Brasil',
    coverage: 'Brasil',
    status: 'active',
    description: 'Bandeira nacional brasileira (Bradesco/BB/Caixa). Forte em conta corrente da população média.',
    supports_nfc: true, nfc_version: 'Elo Contactless 1.5',
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_installments: true,
    max_installments: 18,
    monitoring_programs: ['ELO Risk Monitor'],
    chargeback_threshold_pct: 1.2,
    chargeback_threshold_high_pct: 2.0,
    current_chargeback_pct: 0.62,
    vetoed_mccs: ['7995'],
    tpv_monthly: 4_800_000_000,
    transactions_monthly: 7_200_000,
    approval_rate: 94.2,
    cancellation_rate: 0.41,
    interchange_avg: 2.10,
    scheme_fee_avg: 0.20,
    acquirer_fee_avg: 0.50,
    channel_distribution: { pos: 52, ec: 32, online: 10, pix: 6 },
    modality_distribution: { vista: 48, parc_lojista: 38, parc_emissor: 14 },
    health_score: 84,
  },
  {
    id: 'brand_hipercard',
    name: 'Hipercard',
    logo: 'https://logodownload.org/wp-content/uploads/2017/03/hipercard-logo.png',
    type: 'credit',
    country_origin: 'Brasil',
    coverage: 'Brasil',
    status: 'active',
    description: 'Bandeira regional brasileira (Itaú), forte no Nordeste e em varejo tradicional.',
    supports_nfc: true, nfc_version: '1.0',
    supports_3ds: true, ds_version: '1.0',
    supports_tokenization: false,
    supports_installments: true,
    max_installments: 12,
    monitoring_programs: [],
    chargeback_threshold_pct: 1.5,
    chargeback_threshold_high_pct: 2.5,
    current_chargeback_pct: 0.78,
    vetoed_mccs: [],
    tpv_monthly: 980_000_000,
    transactions_monthly: 1_800_000,
    approval_rate: 92.8,
    cancellation_rate: 0.52,
    interchange_avg: 2.30,
    scheme_fee_avg: 0.22,
    acquirer_fee_avg: 0.52,
    channel_distribution: { pos: 78, ec: 18, online: 4, pix: 0 },
    modality_distribution: { vista: 42, parc_lojista: 48, parc_emissor: 10 },
    health_score: 78,
  },
  {
    id: 'brand_amex',
    name: 'American Express',
    logo: 'https://logodownload.org/wp-content/uploads/2014/03/amex-logo.png',
    type: 'credit',
    country_origin: 'EUA',
    coverage: 'Global',
    status: 'active',
    description: 'Bandeira premium global, alto ticket e baixo volume. Forte em e-commerce e viagens.',
    supports_nfc: true, nfc_version: 'ExpressPay',
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_installments: true,
    max_installments: 12,
    monitoring_programs: ['Amex Fraud Monitoring'],
    chargeback_threshold_pct: 0.8,
    chargeback_threshold_high_pct: 1.5,
    current_chargeback_pct: 0.28,
    vetoed_mccs: ['7995', '5967', '4900', '7273'],
    tpv_monthly: 1_400_000_000,
    transactions_monthly: 720_000,
    approval_rate: 91.4,
    cancellation_rate: 0.38,
    interchange_avg: 2.85,
    scheme_fee_avg: 0.30,
    acquirer_fee_avg: 0.60,
    channel_distribution: { pos: 22, ec: 64, online: 14, pix: 0 },
    modality_distribution: { vista: 78, parc_lojista: 18, parc_emissor: 4 },
    health_score: 90,
  },
  {
    id: 'brand_visa_electron',
    name: 'Visa Electron',
    logo: 'https://logodownload.org/wp-content/uploads/2017/05/visa-logo-0.png',
    type: 'debit',
    country_origin: 'EUA',
    coverage: 'Global',
    status: 'active',
    description: 'Variante de débito da Visa. Sem suporte a parcelamento por design.',
    supports_nfc: true, nfc_version: 'payWave 1.5',
    supports_3ds: true, ds_version: '2.0',
    supports_tokenization: true,
    supports_installments: false,
    max_installments: 1,
    monitoring_programs: ['VAMP'],
    chargeback_threshold_pct: 0.5,
    chargeback_threshold_high_pct: 1.0,
    current_chargeback_pct: 0.12,
    vetoed_mccs: [],
    tpv_monthly: 2_200_000_000,
    transactions_monthly: 5_400_000,
    approval_rate: 97.8,
    cancellation_rate: 0.18,
    interchange_avg: 0.95,
    scheme_fee_avg: 0.10,
    acquirer_fee_avg: 0.25,
    channel_distribution: { pos: 68, ec: 22, online: 8, pix: 2 },
    modality_distribution: { vista: 100, parc_lojista: 0, parc_emissor: 0 },
    health_score: 95,
  },
];

// ================== CANAIS ==================
export const CHANNELS = [
  {
    id: 'ch_pos',
    name: 'POS Físico',
    type: 'presencial',
    status: 'active',
    description: 'Captura presencial via terminal físico (POS, mPOS, smart-POS). Maior taxa de aprovação por presença do portador.',
    capabilities: ['parcelamento', 'nfc', 'emv_chip', '3ds_optional', 'tokenization'],
    acquirers: ['Cielo', 'Rede', 'Stone', 'Getnet'],
    brands_supported: 8,
    tpv_monthly: 18_400_000_000,
    transactions_monthly: 24_500_000,
    approval_rate: 97.8,
    chargeback_rate: 0.12,
    merchants_using: 6420,
    antifraud_rules: 4,
  },
  {
    id: 'ch_ec',
    name: 'E-commerce (Gateway)',
    type: 'online',
    status: 'active',
    description: 'Integração via gateway para lojas online. Inclui 3DS 2.0 obrigatório acima de R$ 500.',
    capabilities: ['parcelamento', 'recorrencia', 'tokenization', '3ds_2_0', 'antifraud_engine'],
    acquirers: ['Cielo', 'Rede', 'Stone', 'Getnet'],
    brands_supported: 7,
    tpv_monthly: 8_900_000_000,
    transactions_monthly: 12_400_000,
    approval_rate: 88.4,
    chargeback_rate: 0.78,
    merchants_using: 3120,
    antifraud_rules: 12,
  },
  {
    id: 'ch_online_api',
    name: 'Online API Direta',
    type: 'online',
    status: 'active',
    description: 'Integração direta via API REST. Para lojistas técnicos com checkout customizado.',
    capabilities: ['parcelamento', 'recorrencia', 'tokenization', '3ds_2_0', 'webhook'],
    acquirers: ['Cielo', 'Stone', 'Getnet'],
    brands_supported: 7,
    tpv_monthly: 4_200_000_000,
    transactions_monthly: 5_800_000,
    approval_rate: 92.1,
    chargeback_rate: 0.42,
    merchants_using: 480,
    antifraud_rules: 8,
  },
  {
    id: 'ch_paylink',
    name: 'Link de Pagamento',
    type: 'online',
    status: 'active',
    description: 'Geração de link único para cobrança remota. Útil para serviços profissionais e cobranças únicas.',
    capabilities: ['parcelamento', 'recorrencia', 'tokenization', '3ds_optional'],
    acquirers: ['Cielo', 'Rede', 'Stone'],
    brands_supported: 6,
    tpv_monthly: 1_800_000_000,
    transactions_monthly: 1_240_000,
    approval_rate: 90.8,
    chargeback_rate: 0.58,
    merchants_using: 1840,
    antifraud_rules: 6,
  },
  {
    id: 'ch_pix_qr',
    name: 'PIX QR',
    type: 'instantaneo',
    status: 'active',
    description: 'Pagamento instantâneo via QR Code (estático ou dinâmico). Sem chargeback por design.',
    capabilities: ['qr_static', 'qr_dynamic', 'webhook', 'instant_settlement'],
    acquirers: ['Cielo', 'Rede', 'Stone', 'Getnet'],
    brands_supported: 0,
    tpv_monthly: 6_400_000_000,
    transactions_monthly: 18_900_000,
    approval_rate: 99.2,
    chargeback_rate: 0,
    merchants_using: 5240,
    antifraud_rules: 3,
  },
  {
    id: 'ch_recurrence',
    name: 'Recorrência (MIT)',
    type: 'online',
    status: 'active',
    description: 'Cobrança recorrente automatizada via tokenização. Para SaaS, assinaturas e mensalidades.',
    capabilities: ['recorrencia', 'tokenization', 'retry_logic', 'dunning'],
    acquirers: ['Cielo', 'Stone'],
    brands_supported: 5,
    tpv_monthly: 980_000_000,
    transactions_monthly: 2_100_000,
    approval_rate: 84.2,
    chargeback_rate: 0.32,
    merchants_using: 720,
    antifraud_rules: 4,
  },
];

// Util de formatação
export const fmtMoney = (v) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', notation: v >= 1_000_000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(v);
export const fmtNumber = (v) => new Intl.NumberFormat('pt-BR').format(v);
export const fmtPct = (v, decimals = 2) => `${(v ?? 0).toFixed(decimals)}%`;