import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Gavel, Save, ArrowLeft, AlertTriangle, FileText, Bell, Target } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/components/utils';
import { toast } from 'sonner';

export default function AdminIntDisputeManagerSettings() {
  const [settings, setSettings] = useState({
    autoContestHighProbability: false,
    highProbabilityThreshold: [80],
    alertsEnabled: true,
    deadlineAlertDays: [5],
    ratioAlertThreshold: [1.2],
    autoGenerateDossier: true,
    notifyMerchantOnDispute: true,
    weeklyReport: true
  });

  const handleSave = () => {
    toast.success('Configurações do Dispute Manager salvas!');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link to={createPageUrl('AdminIntDisputeManager')}>
            <Button variant="ghost" size="icon">
              <ArrowLeft className="w-5 h-5" />
            </Button>
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-red-500 to-orange-500 flex items-center justify-center">
              <Gavel className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-slate-900 dark:text-white">Configurações - Dispute Manager</h1>
              <p className="text-sm text-slate-500">Configurações globais de gestão de disputas</p>
            </div>
          </div>
        </div>
        <Button onClick={handleSave} className="bg-red-600 hover:bg-red-700">
          <Save className="w-4 h-4 mr-2" />
          Salvar
        </Button>
      </div>

      <Tabs defaultValue="automation">
        <TabsList>
          <TabsTrigger value="automation">Automação</TabsTrigger>
          <TabsTrigger value="alerts">Alertas</TabsTrigger>
          <TabsTrigger value="reports">Relatórios</TabsTrigger>
        </TabsList>

        <TabsContent value="automation" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm flex items-center gap-2">
                <Target className="w-4 h-4 text-red-500" />
                Automação de Contestação
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between p-3 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-200">
                <div>
                  <Label className="text-amber-700">Contestar Automaticamente Alta Probabilidade</Label>
                  <p className="text-xs text-amber-600">⚠️ Disputas serão contestadas sem confirmação</p>
                </div>
                <Switch 
                  checked={settings.autoContestHighProbability} 
                  onCheckedChange={(v) => setSettings({...settings, autoContestHighProbability: v})} 
                />
              </div>

              {settings.autoContestHighProbability && (
                <div className="space-y-2 pl-4 border-l-2 border-red-200">
                  <Label>Threshold de Probabilidade: {settings.highProbabilityThreshold}%</Label>
                  <Slider 
                    value={settings.highProbabilityThreshold} 
                    onValueChange={(v) => setSettings({...settings, highProbabilityThreshold: v})}
                    min={50}
                    max={95}
                    step={5}
                  />
                </div>
              )}

              <div className="flex items-center justify-between">
                <div>
                  <Label>Gerar Dossiê Automaticamente</Label>
                  <p className="text-xs text-slate-500">Preparar evidências ao receber disputa</p>
                </div>
                <Switch 
                  checked={settings.autoGenerateDossier} 
                  onCheckedChange={(v) => setSettings({...settings, autoGenerateDossier: v})} 
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label>Notificar Merchant ao Receber Disputa</Label>
                  <p className="text-xs text-slate-500">Enviar email para o merchant</p>
                </div>
                <Switch 
                  checked={settings.notifyMerchantOnDispute} 
                  onCheckedChange={(v) => setSettings({...settings, notifyMerchantOnDispute: v})} 
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="alerts" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-red-500" />
                Configuração de Alertas
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Alertas Habilitados</Label>
                  <p className="text-xs text-slate-500">Receber notificações de disputas</p>
                </div>
                <Switch 
                  checked={settings.alertsEnabled} 
                  onCheckedChange={(v) => setSettings({...settings, alertsEnabled: v})} 
                />
              </div>

              <div className="space-y-2">
                <Label>Alerta de Prazo: {settings.deadlineAlertDays} dias antes</Label>
                <Slider 
                  value={settings.deadlineAlertDays} 
                  onValueChange={(v) => setSettings({...settings, deadlineAlertDays: v})}
                  min={1}
                  max={15}
                  step={1}
                />
              </div>

              <div className="space-y-2">
                <Label>Alerta de Chargeback Ratio: acima de {settings.ratioAlertThreshold}%</Label>
                <Slider 
                  value={settings.ratioAlertThreshold} 
                  onValueChange={(v) => setSettings({...settings, ratioAlertThreshold: v})}
                  min={0.5}
                  max={2}
                  step={0.1}
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="reports" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm flex items-center gap-2">
                <FileText className="w-4 h-4 text-red-500" />
                Relatórios Automáticos
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Relatório Semanal de Disputas</Label>
                  <p className="text-xs text-slate-500">Resumo enviado toda segunda-feira</p>
                </div>
                <Switch 
                  checked={settings.weeklyReport} 
                  onCheckedChange={(v) => setSettings({...settings, weeklyReport: v})} 
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}