// Mock data para componentes de Orquestração + Multi-Method + Split (Tuna integration)

export const mockMultiMethodTransactions = [
  {
    id: 'tx_001',
    paymentKey: '134D946015A08C9',
    partnerUniqueId: '#000.001',
    totalAmount: 5000,
    customerName: 'João da Silva',
    customerEmail: 'joao@example.com',
    createdAt: '2026-05-09T14:32:00',
    status: 'authorized',
    flow: 'High-Ticket Multi-Method',
    methods: [
      { methodKey: 'mk_a1', type: 'credit_card', brand: 'Visa', last4: '4242', amount: 2000, installments: 10, interestType: 'merchant', acquirer: 'Cielo', status: 'authorized' },
      { methodKey: 'mk_a2', type: 'credit_card', brand: 'Master', last4: '1111', amount: 2000, installments: 10, interestType: 'merchant', acquirer: 'Rede', status: 'authorized' },
      { methodKey: 'mk_a3', type: 'pix', endToEndId: 'E60701190202407101759DY5BQ4HFISM', amount: 1000, status: 'pending' },
    ],
  },
  {
    id: 'tx_002',
    paymentKey: '134D946015A08D2',
    partnerUniqueId: '#000.002',
    totalAmount: 1500,
    customerName: 'Maria Souza',
    customerEmail: 'maria@example.com',
    createdAt: '2026-05-09T13:15:00',
    status: 'captured',
    flow: 'Cartão+PIX Standard',
    methods: [
      { methodKey: 'mk_b1', type: 'credit_card', brand: 'Visa', last4: '8888', amount: 1000, installments: 6, interestType: 'merchant', acquirer: 'Cielo', status: 'captured' },
      { methodKey: 'mk_b2', type: 'pix', endToEndId: 'E60701190202407101759XB7AB9D2X', amount: 500, status: 'captured' },
    ],
  },
  {
    id: 'tx_003',
    paymentKey: '134D946015A08E7',
    partnerUniqueId: '#000.003',
    totalAmount: 800,
    customerName: 'Pedro Almeida',
    customerEmail: 'pedro@example.com',
    createdAt: '2026-05-09T11:45:00',
    status: 'authorized',
    flow: 'Cartão+Boleto',
    methods: [
      { methodKey: 'mk_c1', type: 'credit_card', brand: 'Elo', last4: '3344', amount: 500, installments: 3, interestType: 'customer', acquirer: 'Getnet', status: 'authorized' },
      { methodKey: 'mk_c2', type: 'boleto', amount: 300, status: 'pending' },
    ],
  },
  {
    id: 'tx_004',
    paymentKey: '134D946015A08F1',
    partnerUniqueId: '#000.004',
    totalAmount: 12000,
    customerName: 'Carlos Rocha',
    customerEmail: 'carlos@empresa.com',
    createdAt: '2026-05-09T10:22:00',
    status: 'authorized',
    flow: 'Enterprise 2C+PIX',
    methods: [
      { methodKey: 'mk_d1', type: 'credit_card', brand: 'Visa', last4: '5555', amount: 5000, installments: 12, interestType: 'merchant', acquirer: 'Adyen', status: 'authorized' },
      { methodKey: 'mk_d2', type: 'credit_card', brand: 'Master', last4: '7777', amount: 5000, installments: 12, interestType: 'merchant', acquirer: 'Cielo', status: 'authorized' },
      { methodKey: 'mk_d3', type: 'pix', endToEndId: 'E60701190202407101759ABC123XYZ', amount: 2000, status: 'captured' },
    ],
  },
];

export const mockMultiMethodKpis = {
  totalTransactions: 8432,
  multiMethodCount: 1287,
  multiMethodRate: 15.3,
  avgTicketSingle: 287.50,
  avgTicketMulti: 2843.20,
  conversionLift: 23.8,
  recoveryRate: 18.4,
  distribution: [
    { combination: '1 Método', count: 7145, percent: 84.7, avgTicket: 287.50 },
    { combination: 'Cartão + PIX', count: 612, percent: 7.3, avgTicket: 1843.20 },
    { combination: '2 Cartões', count: 387, percent: 4.6, avgTicket: 3120.50 },
    { combination: 'Cartão + Boleto', count: 198, percent: 2.4, avgTicket: 2245.80 },
    { combination: '2 Cartões + PIX', count: 67, percent: 0.8, avgTicket: 8945.00 },
    { combination: 'Crédito + Débito', count: 23, percent: 0.3, avgTicket: 645.00 },
  ],
};

export const mockConnections = [
  // Adquirentes
  { id: 'cielo', name: 'Cielo', type: 'acquirer', methods: ['credit', 'debit'], status: 'healthy', latencyP50: 245, latencyP95: 580, latencyP99: 1240, errorRate: 0.3, approvalRate: 87.4, uptime: 99.97 },
  { id: 'rede', name: 'Rede', type: 'acquirer', methods: ['credit'], status: 'healthy', latencyP50: 312, latencyP95: 720, latencyP99: 1520, errorRate: 0.5, approvalRate: 85.1, uptime: 99.92 },
  { id: 'getnet', name: 'Getnet', type: 'acquirer', methods: ['credit'], status: 'degraded', latencyP50: 580, latencyP95: 1840, latencyP99: 4500, errorRate: 2.1, approvalRate: 78.3, uptime: 98.45 },
  { id: 'pagseguro', name: 'PagSeguro', type: 'acquirer', methods: ['credit'], status: 'healthy', latencyP50: 290, latencyP95: 650, latencyP99: 1380, errorRate: 0.4, approvalRate: 84.2, uptime: 99.91 },
  { id: 'adyen', name: 'Adyen', type: 'acquirer', methods: ['credit'], status: 'healthy', latencyP50: 198, latencyP95: 420, latencyP99: 890, errorRate: 0.2, approvalRate: 91.2, uptime: 99.99 },
  { id: 'mercadopago', name: 'Mercado Pago', type: 'acquirer', methods: ['credit', 'pix', 'boleto'], status: 'healthy', latencyP50: 320, latencyP95: 780, latencyP99: 1620, errorRate: 0.6, approvalRate: 86.8, uptime: 99.85 },
  { id: 'bb', name: 'Banco do Brasil', type: 'acquirer', methods: ['pix', 'boleto'], status: 'healthy', latencyP50: 412, latencyP95: 980, latencyP99: 2100, errorRate: 0.4, approvalRate: 95.2, uptime: 99.88 },
  { id: 'itau', name: 'Itaú', type: 'acquirer', methods: ['pix'], status: 'healthy', latencyP50: 380, latencyP95: 850, latencyP99: 1740, errorRate: 0.3, approvalRate: 96.1, uptime: 99.94 },
  { id: 'santander', name: 'Santander', type: 'acquirer', methods: ['boleto'], status: 'healthy', latencyP50: 520, latencyP95: 1240, latencyP99: 2680, errorRate: 0.5, approvalRate: 94.8, uptime: 99.81 },
  { id: 'gerencianet', name: 'Gerencianet', type: 'acquirer', methods: ['pix'], status: 'healthy', latencyP50: 410, latencyP95: 920, latencyP99: 1980, errorRate: 0.4, approvalRate: 95.7, uptime: 99.89 },
  { id: 'nupay', name: 'Nu Pay', type: 'acquirer', methods: ['pix'], status: 'healthy', latencyP50: 280, latencyP95: 620, latencyP99: 1320, errorRate: 0.3, approvalRate: 96.5, uptime: 99.92 },
  { id: 'bancryp', name: 'Bancryp', type: 'acquirer', methods: ['crypto'], status: 'down', latencyP50: 0, latencyP95: 0, latencyP99: 0, errorRate: 100, approvalRate: 0, uptime: 87.40 },
  { id: 'sitef', name: 'Sitef', type: 'acquirer', methods: ['credit'], status: 'healthy', latencyP50: 340, latencyP95: 780, latencyP99: 1640, errorRate: 0.6, approvalRate: 83.9, uptime: 99.78 },
  // Gateways
  { id: 'braspag', name: 'Braspag', type: 'gateway', methods: ['credit'], status: 'healthy', latencyP50: 220, latencyP95: 480, latencyP99: 980, errorRate: 0.2, approvalRate: 88.7, uptime: 99.95 },
  { id: 'pagarme', name: 'Pagar.me', type: 'gateway', methods: ['credit', 'pix', 'boleto'], status: 'healthy', latencyP50: 265, latencyP95: 590, latencyP99: 1180, errorRate: 0.3, approvalRate: 87.9, uptime: 99.93 },
  // Antifraudes
  { id: 'clearsale', name: 'ClearSale', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 380, latencyP95: 920, latencyP99: 1980, errorRate: 0.5, approvalRate: null, uptime: 99.84 },
  { id: 'cybersource', name: 'Cybersource', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 290, latencyP95: 720, latencyP99: 1540, errorRate: 0.3, approvalRate: null, uptime: 99.92 },
  { id: 'konduto', name: 'Konduto', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 320, latencyP95: 780, latencyP99: 1640, errorRate: 0.4, approvalRate: null, uptime: 99.88 },
  { id: 'koin', name: 'Koin', type: 'antifraud', methods: [], status: 'degraded', latencyP50: 680, latencyP95: 1840, latencyP99: 4200, errorRate: 1.8, approvalRate: null, uptime: 98.65 },
  { id: 'sift', name: 'Sift', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 240, latencyP95: 560, latencyP99: 1180, errorRate: 0.3, approvalRate: null, uptime: 99.94 },
  { id: 'signifyd', name: 'Signifyd', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 280, latencyP95: 680, latencyP99: 1380, errorRate: 0.4, approvalRate: null, uptime: 99.91 },
  { id: 'tuna_af', name: 'Tuna Anti-fraud', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 180, latencyP95: 420, latencyP99: 890, errorRate: 0.2, approvalRate: null, uptime: 99.97 },
  { id: 'tuna_velocity', name: 'Tuna Velocity', type: 'antifraud', methods: [], status: 'healthy', latencyP50: 95, latencyP95: 220, latencyP99: 480, errorRate: 0.1, approvalRate: null, uptime: 99.99 },
  { id: 'quod', name: 'Quod (docs)', type: 'identity', methods: [], status: 'healthy', latencyP50: 1240, latencyP95: 2980, latencyP99: 5400, errorRate: 0.6, approvalRate: null, uptime: 99.74 },
  { id: 'unico', name: 'Unico ID (biometria)', type: 'identity', methods: [], status: 'healthy', latencyP50: 980, latencyP95: 2240, latencyP99: 4200, errorRate: 0.5, approvalRate: null, uptime: 99.82 },
];

export const mockRecoveryFunnel = {
  declines: 4823,
  recoveryAttempted: 4651,
  recovered: 856,
  recoveryRate: 18.4,
  byMethod: [
    { method: 'PIX (5% off)', recovered: 412, percent: 48.1, avgTicket: 285 },
    { method: 'Cartão alternativo', recovered: 198, percent: 23.1, avgTicket: 645 },
    { method: 'Apple Pay / Google Pay', recovered: 124, percent: 14.5, avgTicket: 412 },
    { method: 'Boleto', recovered: 87, percent: 10.2, avgTicket: 1240 },
    { method: 'Multi-método', recovered: 35, percent: 4.1, avgTicket: 2840 },
  ],
  byDeclineReason: [
    { reason: 'Insufficient Funds (NSF)', count: 1842, recovered: 412, rate: 22.4 },
    { reason: 'Do Not Honor (DNH)', count: 1284, recovered: 198, rate: 15.4 },
    { reason: 'Hard Decline', count: 687, recovered: 24, rate: 3.5 },
    { reason: 'Issuer Unavailable', count: 412, recovered: 162, rate: 39.3 },
    { reason: 'Velocity', count: 287, recovered: 38, rate: 13.2 },
    { reason: 'Card Expired', count: 311, recovered: 22, rate: 7.1 },
  ],
  revenueRecovered: 612480.50,
};

export const mockOrchestrationFlows = [
  {
    id: 'flow_001',
    name: 'High-ticket Routing',
    description: 'Roteia tickets > R$ 1.000 para Adyen, com fallback Cielo',
    isActive: true,
    volume: 1284,
    successRate: 91.4,
    nodes: [
      { id: 1, type: 'trigger', label: 'payment.init', config: { event: 'payment.init' } },
      { id: 2, type: 'condition', label: 'amount > 1000', config: { rule: 'amount > 1000' } },
      { id: 3, type: 'acquirer', label: 'Adyen (premium)', config: { acquirer: 'adyen', timeout: 8 } },
      { id: 4, type: 'fallback', label: 'Cielo', config: { acquirer: 'cielo', after: 'soft_decline' } },
    ],
  },
  {
    id: 'flow_002',
    name: 'PIX-First Subscriptions',
    description: 'Assinaturas tentam PIX automático antes de cartão',
    isActive: true,
    volume: 4827,
    successRate: 88.9,
    nodes: [
      { id: 1, type: 'trigger', label: 'subscription.charge', config: {} },
      { id: 2, type: 'acquirer', label: 'PIX automático', config: { method: 'pix' } },
      { id: 3, type: 'fallback', label: 'Cartão saved', config: {} },
    ],
  },
  {
    id: 'flow_003',
    name: 'BIN-Based Routing',
    description: 'Visa/Master para Adyen; Elo para Cielo; Hipercard para Rede',
    isActive: true,
    volume: 8412,
    successRate: 87.2,
    nodes: [
      { id: 1, type: 'trigger', label: 'payment.init', config: {} },
      { id: 2, type: 'condition', label: 'BIN check', config: { rule: 'bin.brand' } },
      { id: 3, type: 'acquirer', label: 'Smart route', config: {} },
    ],
  },
  {
    id: 'flow_004',
    name: 'Recurring Card-on-File',
    description: 'Pagamentos de assinatura usando token armazenado',
    isActive: false,
    volume: 0,
    successRate: 0,
    nodes: [
      { id: 1, type: 'trigger', label: 'recurring.attempt', config: {} },
      { id: 2, type: 'action', label: 'Use token vault', config: {} },
    ],
  },
];

export const mockSmartSplitSuggestions = [
  {
    id: 'sgst_001',
    merchantName: 'Marketplace Beleza Pro',
    currentSplits: { master: 8, sublojistas: 92 },
    suggested: { master: 12, sublojistas: 88 },
    reason: 'Volume médio dos sub-lojistas é 18% superior ao baseline e suporta margem',
    expectedRevenueLift: 24800,
    confidence: 0.87,
  },
  {
    id: 'sgst_002',
    merchantName: 'Cestas Gourmet ME',
    currentSplits: { master: 15, sublojistas: 85 },
    suggested: { master: 10, sublojistas: 90 },
    reason: 'Alto churn de sub-lojistas e margem competitiva inferior ao mercado',
    expectedRevenueLift: -3400,
    expectedRetention: 12,
    confidence: 0.79,
  },
  {
    id: 'sgst_003',
    merchantName: 'Fashion Hub LTDA',
    currentSplits: { master: 10, sublojistas: 90 },
    suggested: { master: 10, sublojistas: 90, plus_processing_fee: 'sublojistas' },
    reason: 'Recomendado mover charge_processing_fee para sub-lojistas (não impacta MDR)',
    expectedRevenueLift: 8920,
    confidence: 0.92,
  },
];

export const mockABAllocations = [
  {
    id: 'ab_001',
    name: '3DS Adaptativo (cartão)',
    status: 'running',
    startedAt: '2026-04-22',
    variants: [
      { id: 'A', label: 'Controle (3DS sempre)', volume: 8420, conversion: 84.2, mdr: 1.99, allocation: 50 },
      { id: 'B', label: 'Tratamento (3DS adaptativo)', volume: 8392, conversion: 87.6, mdr: 2.04, allocation: 50 },
    ],
    significance: 0.96,
    winner: 'B',
    revenueLift: 18420,
  },
  {
    id: 'ab_002',
    name: 'PIX 5% off vs Boleto',
    status: 'running',
    startedAt: '2026-04-30',
    variants: [
      { id: 'A', label: 'Boleto como fallback', volume: 1240, conversion: 21.4, mdr: 0, allocation: 50 },
      { id: 'B', label: 'PIX 5% off', volume: 1218, conversion: 38.2, mdr: 0.99, allocation: 50 },
    ],
    significance: 0.99,
    winner: 'B',
    revenueLift: 32180,
  },
  {
    id: 'ab_003',
    name: 'Adyen vs Cielo (high-ticket)',
    status: 'paused',
    startedAt: '2026-04-15',
    variants: [
      { id: 'A', label: 'Adyen 100%', volume: 412, conversion: 91.2, mdr: 2.49, allocation: 0 },
      { id: 'B', label: 'Cielo 100%', volume: 388, conversion: 87.4, mdr: 1.99, allocation: 0 },
    ],
    significance: 0.84,
    winner: null,
    revenueLift: null,
  },
];

export const mockShadowTests = [
  { id: 1, name: 'Adyen Latam (sandbox)', status: 'running', requestsShadow: 12842, errorsShadow: 124, latencyDeltaMs: -45, divergenceRate: 0.024 },
  { id: 2, name: 'New antifraud rule v2.3', status: 'running', requestsShadow: 8412, errorsShadow: 0, latencyDeltaMs: 12, divergenceRate: 0.068 },
  { id: 3, name: 'PIX Express discount', status: 'completed', requestsShadow: 24180, errorsShadow: 18, latencyDeltaMs: 0, divergenceRate: 0.001 },
];

export const mockReconciliation = {
  totalRecords: 184232,
  reconciled: 182417,
  divergent: 1620,
  pending: 195,
  rate: 99.0,
  divergencesByType: [
    { type: 'Valor divergente (centavos)', count: 412, totalAmount: 1248.30 },
    { type: 'Adquirente sem extrato', count: 287, totalAmount: 84320.00 },
    { type: 'Refund duplicado', count: 142, totalAmount: 12480.50 },
    { type: 'MED não correspondente', count: 87, totalAmount: 4280.00 },
    { type: 'Status divergente', count: 692, totalAmount: 134820.00 },
  ],
  byAcquirer: [
    { acquirer: 'Cielo', expected: 412840, received: 412840, rate: 100 },
    { acquirer: 'Adyen', expected: 284120, received: 284115, rate: 99.998 },
    { acquirer: 'Rede', expected: 198320, received: 197890, rate: 99.78 },
    { acquirer: 'Getnet', expected: 124180, received: 122340, rate: 98.52 },
    { acquirer: 'Mercado Pago', expected: 98420, received: 98412, rate: 99.99 },
  ],
};

export const mockFraudAnomalies = [
  {
    id: 1,
    severity: 'critical',
    type: 'velocity_spike',
    title: 'Spike de velocidade detectado',
    description: 'Cartão BIN 411111 registrou 47 tentativas em 8 minutos no merchant Loja XYZ',
    detectedAt: '2026-05-09T13:22:00',
    affectedTransactions: 47,
    estimatedLoss: 18420,
    score: 94,
    status: 'open',
  },
  {
    id: 2,
    severity: 'high',
    type: 'geo_anomaly',
    title: 'Anomalia geográfica',
    description: 'Padrão de transações de IPs em 14 países diferentes para mesmo CPF em 2h',
    detectedAt: '2026-05-09T12:15:00',
    affectedTransactions: 23,
    estimatedLoss: 4280,
    score: 87,
    status: 'investigating',
  },
  {
    id: 3,
    severity: 'medium',
    type: 'card_testing',
    title: 'Card testing em massa',
    description: 'Aumento de 340% em pequenos valores (R$ 1-5) com cartões diferentes',
    detectedAt: '2026-05-09T10:42:00',
    affectedTransactions: 184,
    estimatedLoss: 920,
    score: 72,
    status: 'mitigated',
  },
  {
    id: 4,
    severity: 'medium',
    type: 'chargeback_cluster',
    title: 'Cluster de chargebacks',
    description: '12 chargebacks no mesmo dia para merchant que historicamente tem 0-1/dia',
    detectedAt: '2026-05-08T18:00:00',
    affectedTransactions: 12,
    estimatedLoss: 28940,
    score: 68,
    status: 'open',
  },
];

export const mockMerchantCoverageMatrix = [
  {
    merchantId: 'mch_001',
    name: 'Loja Eletronica BR Ltda',
    document: '12.345.678/0001-99',
    tenant: 'Marketplace ABC',
    services: {
      'pix_69': 'active',
      'pix_71': 'active',
      'pix_86': 'pending',
      'pix_88': 'active',
      'pix_93': 'active',
      'pix_101': 'rejected',
      'card_41': 'active',
      'card_63': 'active',
    },
  },
  {
    merchantId: 'mch_002',
    name: 'Moda Express ME',
    document: '98.765.432/0001-11',
    tenant: 'Marketplace XYZ',
    services: {
      'pix_69': 'active',
      'pix_71': 'pending',
      'pix_86': 'inactive',
      'pix_88': 'active',
      'pix_93': 'inactive',
      'pix_101': 'inactive',
      'card_41': 'active',
      'card_63': 'pending',
    },
  },
  {
    merchantId: 'mch_003',
    name: 'Doces Caseiros LTDA',
    document: '11.222.333/0001-44',
    tenant: 'Marketplace DEF',
    services: {
      'pix_69': 'active',
      'pix_71': 'active',
      'pix_86': 'active',
      'pix_88': 'active',
      'pix_93': 'rejected',
      'pix_101': 'inactive',
      'card_41': 'active',
      'card_63': 'inactive',
    },
  },
  {
    merchantId: 'mch_004',
    name: 'Esporte Total Ltda',
    document: '55.444.333/0001-22',
    tenant: 'Marketplace ABC',
    services: {
      'pix_69': 'active',
      'pix_71': 'active',
      'pix_86': 'active',
      'pix_88': 'active',
      'pix_93': 'active',
      'pix_101': 'active',
      'card_41': 'active',
      'card_63': 'active',
    },
  },
  {
    merchantId: 'mch_005',
    name: 'Casa do Bebê',
    document: '77.888.999/0001-55',
    tenant: 'Marketplace XYZ',
    services: {
      'pix_69': 'pending',
      'pix_71': 'pending',
      'pix_86': 'inactive',
      'pix_88': 'inactive',
      'pix_93': 'inactive',
      'pix_101': 'inactive',
      'card_41': 'pending',
      'card_63': 'inactive',
    },
  },
];